#add custom theme snippets here
decoration { 
        rounding = 4
        active_opacity = 1
        inactive_opacity = 1
    shadow {
        enabled = false
        color = $background
        range = 30
        color_inactive = $color0
        render_power = 50
      }
     blur {
        size = 20
        passes = 4
        noise = 0.05
        vibrancy = 1
        }
}
general { 
    border_size = 3
    col.active_border = $color3
    col.inactive_border = 00000000
    gaps_in = 2
    gaps_out = 6
}

 animations {

    bezier = cubicsome, .72,  .46,  .74,  .77
      
      animation = windowsIn, 1,2, cubicsome
      animation = layers, 1,2, cubicsome
      animation = windowsOut, 1, 2, cubicsome
      animation = border, 0
      animation = borderangle, 0
      animation = fade, 1, 4.5, default
      animation = workspaces, 1, 4, cubicsome, fade
      animation = specialWorkspace, 1, 6, default, slidevert
 }
