foreground         #c8d3f5
background         #222436
background_opacity 1.0
cursor             #c8d3f5

active_tab_foreground     #222436
active_tab_background     #c8d3f5
inactive_tab_foreground   #c8d3f5
inactive_tab_background   #222436

active_border_color   #c8d3f5
inactive_border_color #222436
bell_border_color     #ff757f

color0       #1b1d2b
color8       #444a73
color1       #ff757f
color9       #ff8d94
color2       #c3e88d
color10      #c7fb6d
color3       #ffc777
color11      #ffd8ab
color4       #82aaff
color12      #9ab8ff
color5       #c099ff
color13      #caabff
color6       #86e1fc
color14      #b2ebff
color7       #828bb8
color15      #c8d3f5
