--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#222436"
foreground="#c8d3f5"
cursor="#c8d3f5"

-- Colors
color0="#1b1d2b"
color1="#ff757f"
color2="#c3e88d"
color3="#ffc777"
color4="#82aaff"
color5="#c099ff"
color6="#86e1fc"
color7="#828bb8"
color8="#444a73"
color9="#ff8d94"
color10="#c7fb6d"
color11="#ffd8ab"
color12="#9ab8ff"
color13="#caabff"
color14="#b2ebff"
color15="#c8d3f5"
