[colors]
background = '#2224368e'
black = '#1b1d2b'
blue = '#ff757f'
cursor = '#c8d3f5'
cyan = '#c3e88d'
foreground = '#c8d3f5'
green = '#ffc777'
magenta = '#82aaff'
red = '#c099ff'
tabs = '#c8d3f5'
tabs-active = '#86e1fc'
white = '#c8d3f5'
yellow = '#828bb8'
dim-black = '#1b1d2b8e'
dim-blue = '#ff757f8e'
dim-cyan = '#c3e88d8e'
dim-foreground = '#c8d3f58e'
dim-green = '#ffc7778e'
dim-magenta = '#82aaff8e'
dim-red = '#c099ff8e'
dim-white = '#86e1fc8e'
dim-yellow = '#828bb88e'
light-black = '#ff8d94'
light-blue = '#c7fb6d'
light-cyan = '#ffd8ab'
light-foreground = '#9ab8ff'
light-green = '#caabff'
light-magenta = '#b2ebff'
light-red = '#c8d3f5'
light-white = '#ff8d94'
light-yellow = '#c7fb6d'
