# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#222436'
foreground='#c8d3f5'
cursor='#c8d3f5'

# Colors
color0='#1b1d2b'
color1='#ff757f'
color2='#c3e88d'
color3='#ffc777'
color4='#82aaff'
color5='#c099ff'
color6='#86e1fc'
color7='#828bb8'
color8='#444a73'
color9='#ff8d94'
color10='#c7fb6d'
color11='#ffd8ab'
color12='#9ab8ff'
color13='#caabff'
color14='#b2ebff'
color15='#c8d3f5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
