[colors.primary]
background = "#222436"
foreground = "#c8d3f5"

[colors.cursor]
text = "#222436"
cursor = "#c8d3f5"

[colors.vi_mode_cursor]
text = "#222436"
cursor = "#c8d3f5"

[colors.search.matches]
foreground = "#1b1d2b"
background = "#c8d3f5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#444a73"
background = "#828bb8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1b1d2b"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#828bb8"

[colors.bright]
black = "#444a73"
red = "#ff8d94"
green = "#c7fb6d"
yellow = "#ffd8ab"
blue = "#9ab8ff"
magenta = "#caabff"
cyan = "#b2ebff"
white = "#c8d3f5"

[colors.dim]
black = "#c8d3f5"
red = "#ff8d94"
green = "#caabff"
yellow = "#ffd8ab"
blue = "#9ab8ff"
magenta = "#c7fb6d"
cyan = "#b2ebff"
white = "#444a73"

