alias pi='yay -S '
alias piq='yay -S --noconfirm '
alias pmi='sudo pacman -S '
alias clc='sudo pacman -Scc'
alias pcc='sudo pacman -Rcns $(pacman -Qtdq)'
alias xx='exit'
alias prem='sudo pacman -Rcns '
alias hyr='hyprctl reload'
alias ged='gnome-text-editor '
#alias sd='systemctl poweroff'
#alias lout='hyprctl dispatch exit'
alias upd='sudo pacman -Syu'

