# Shell variables
# Generated by 'wal'
wallpaper="/home/papa/X11Scripts/wallpapers/riverEf.png"

# Special
background='#0f241a'
foreground='#c3c8c5'
cursor='#c3c8c5'

# Colors
color0='#0f241a'
color1='#46594C'
color2='#506759'
color3='#6B6654'
color4='#597164'
color5='#67796D'
color6='#73837A'
color7='#c3c8c5'
color8='#5e746a'
color9='#46594C'
color10='#506759'
color11='#6B6654'
color12='#597164'
color13='#67796D'
color14='#73837A'
color15='#c3c8c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
