[colors]
background = '#0f241a8e'
black = '#0f241a'
blue = '#46594C'
cursor = '#c3c8c5'
cyan = '#506759'
foreground = '#c3c8c5'
green = '#6B6654'
magenta = '#597164'
red = '#67796D'
tabs = '#c3c8c5'
tabs-active = '#73837A'
white = '#c3c8c5'
yellow = '#c3c8c5'
dim-black = '#0f241a8e'
dim-blue = '#46594C8e'
dim-cyan = '#5067598e'
dim-foreground = '#c3c8c58e'
dim-green = '#6B66548e'
dim-magenta = '#5971648e'
dim-red = '#67796D8e'
dim-white = '#73837A8e'
dim-yellow = '#c3c8c58e'
light-black = '#46594C'
light-blue = '#506759'
light-cyan = '#6B6654'
light-foreground = '#597164'
light-green = '#67796D'
light-magenta = '#73837A'
light-red = '#c3c8c5'
light-white = '#46594C'
light-yellow = '#506759'
