foreground         #c3c8c5
background         #0f241a
background_opacity 1.0
cursor             #c3c8c5

active_tab_foreground     #0f241a
active_tab_background     #c3c8c5
inactive_tab_foreground   #c3c8c5
inactive_tab_background   #0f241a

active_border_color   #c3c8c5
inactive_border_color #0f241a
bell_border_color     #46594C

color0       #0f241a
color8       #5e746a
color1       #46594C
color9       #46594C
color2       #506759
color10      #506759
color3       #6B6654
color11      #6B6654
color4       #597164
color12      #597164
color5       #67796D
color13      #67796D
color6       #73837A
color14      #73837A
color7       #c3c8c5
color15      #c3c8c5
