# pywal theme for ghostty

background = 0f241a
foreground = c3c8c5
cursor-color = c3c8c5
selection-background = c3c8c5
selection-foreground = 0f241a

palette = 0=#0f241a
palette = 1=#46594C
palette = 2=#506759
palette = 3=#6B6654
palette = 4=#597164
palette = 5=#67796D
palette = 6=#73837A
palette = 7=#c3c8c5
palette = 8=#5e746a
palette = 9=#46594C
palette = 10=#506759
palette = 11=#6B6654
palette = 12=#597164
palette = 13=#67796D
palette = 14=#73837A
palette = 15=#c3c8c5
