#add custom theme snippets here

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 6
        passes = 6
        new_optimizations = on
        ignore_opacity = true
        xray = 0
        # blurls = waybar
    }

    shadow {
        enabled = true
        range = 30
        render_power = 3
        color = 0x66000000
    }
}

general {
    gaps_in = 7
    gaps_out = 7
    border_size = 4
    col.active_border = $color11
    col.inactive_border = $color8
    layout = dwindle
    resize_on_border = true
}

# animations {
#     enabled = true
#     bezier = overshot, 0.05, 0.9, 0.1, 1.05
#     bezier = smoothOut, 0.5, 0, 0.99, 0.99
#     bezier = smoothIn, 0.5, -0.5, 0.68, 1.5
#     animation = windows, 1, 5, overshot, slidefade20%
#     animation = windowsOut, 1, 3, smoothOut
#     animation = windowsIn, 1, 3, smoothOut
#     animation = windowsMove, 1, 4, smoothIn, slidefade 20%
#     animation = border, 1, 5, default
#     animation = fade, 1, 5, smoothIn
#     animation = fadeDim, 1, 5, smoothIn
#     animation = workspaces, 1, 6, default
# }

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    # Commented out due to compatibility reasons
    # new_status = master
}

gestures {
  workspace_swipe = true
  workspace_swipe_fingers = 3
  workspace_swipe_distance = 500
  workspace_swipe_invert = true
  workspace_swipe_min_speed_to_force = 30
  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = true
  workspace_swipe_forever = true
}

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}
