#add custom theme snippets here
decoration { 
        rounding = 8
        active_opacity = 0.90
        inactive_opacity = 0.90
    shadow {
        enabled = true
        color = $background
        range = 30
        color_inactive = $color0
        render_power = 50
      }
     blur {
        size = 6
        passes = 2
        noise = 0.02
        vibrancy = 0.5
        }
}
general { 
    border_size = 4
    col.active_border = $color3
    col.inactive_border = $color0
    gaps_in = 6
#    gaps_in = 5
    gaps_out = 12
}

 animations {
    bezier = cubicsome, 0.72,  0.46,  0.74, 0.77
    bezier = suuu, 0.93, -0.09, 0.18, 0.77
    bezier = neomm,  0, 0.52, 0.3, 0.49

###      animation = windows, 1,2, cubicsome, popin
#      animation = windowsIn, 1,1.5, neomm, popin 40%
#      animation = layers, 1,2, cubicsome , popin 40%
#      animation = windowsOut, 1, 2, cubicsome , slidefade 40%
#      animation = layersOut, 1,2, cubicsome , fade 40%
#      animation = border, 0
#      animation = borderangle, 0
#      animation = fade, 1, 4.5, neomm
##      animation = workspaces, 1, 4, cubicsome, fade
#      animation = workspaces, 1, 2.5, neomm, slidefade 10%
#      animation = specialWorkspace, 1, 6, cubicsome, slidevert

###1, 2.5, neomm, slidefade 10%

      animation = windows, 1, 2.5, neomm, slidefade 10%
      animation = windowsIn,1, 2.5, neomm, slidefade 10%
      animation = layers,1, 2.5, neomm, slidefade 10%
      animation = windowsOut,1, 2.5, neomm, slidefade 10%
      animation = layersOut,1, 2.5, neomm, slidefade 10%
      animation = workspaces,1, 2.5, neomm, slidefade 10%
      animation = specialWorkspace,1, 2.5, neomm, slidefade 10%
      animation = fade,1, 2.5, neomm
      animation = border, 0
      animation = borderangle, 0
 }
