#add custom theme snippets here

decoration {
    rounding = 18
    active_opacity = 0.7
    inactive_opacity = 0.5
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 16
        passes = 4
        new_optimizations = on
        ignore_opacity = true
        xray = 0
        # blurls = waybar
    }

    shadow {
        enabled = true
        range = 30
        render_power = 3
        color = 0x66000000
    }
}

general {
    gaps_in = 8
    gaps_out = 18
    border_size = 3
    col.active_border = $color11
    col.inactive_border = $color8
    layout = dwindle
    resize_on_border = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

gestures {
#  workspace_swipe = true
#  workspace_swipe_fingers = 3
#  workspace_swipe_distance = 500
  workspace_swipe_invert = true
#  workspace_swipe_min_speed_to_force = 30
#  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = true
  workspace_swipe_forever = true
}
